export const categories = [
  "Ballon d'Or",
  'Bundesliga',
  'CL',
  'CR7',
  'LFC',
  'MCFC',
  'MUFC',
  'PL',
  'PSG',
  'balkan',
  'captains',
  'clubs',
  'colors',
  'countries',
  'euro',
  'football',
  'france',
  'germany',
  'goals',
  'goeshard',
  'host',
  'international',
  'italy',
  'laliga',
  'managers',
  'modern',
  'mundial',
  'mundial1998',
  'mundial2002',
  'mundial2006',
  'mundial2010',
  'nicknames',
  'players',
  'records',
  'rivalries',
  'stadiums',
  'topscorers',
  'transfers',
  'winners'
]

export const levels = [
  {'id': 0, 'label': 'Very Easy', 'score': 10},
  {'id': 1, 'label': 'Easy', 'score': 20},
  {'id': 2, 'label': 'Medium', 'score': 50},
  {'id': 3, 'label': 'Hard', 'score': 100},
  {'id': 4, 'label': 'Very Hard', 'score': 150},
  {'id': 5, 'label': 'Insane', 'score': 250}
]
